services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: mydb
      MYSQL_USER: sudosu
      MYSQL_PASSWORD: ABCDE12345
      MYSQL_ROOT_PASSWORD: 12345ABCDE
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "20001:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "20002:80"

volumes:
  db_data: